### PR TITLE
Add blocks for customizing UITextView and UITableViewCell

### PR DESCRIPTION
**Pull request by sodastsai**

### CODE REVIEW

**Comment by vtourraine** [comment]
Hi, thanks for the contribution. :+1: I’m hesitant to merge it, though, because I would suggest subclassing the whole classes for this kind of advanced customization. Sure, both approches are valid, but I’d tend to support simplicity in this case.

It would be interesting to get other people’s feedback on this. Anyone?

**Comment by Ricardo1980** [comment]
I agree with you. 
KISS. 

Enviado desde mi iPhone.

**Comment by sodastsai** [comment]
Originally I wanted to use a subclass in my app :smile:
But I found there are some property like ```licenseTextViewFont``` for customizing appearances, that's why I added such blocks. (I wanna change also text color and background).

Indeed, using such a customizing block is weird and also I don't find other projects doing so. If possible, could I add some new properties like ```licenseTextViewTextColor``` for customization?

**Comment by vtourraine** [comment]
Yeah, now that I think about it, this `textViewFont` property might not be the best idea. I might take it off before the v1.0.

What we could add, instead, is a `textView` property to make it easier to subclass and manipulate it if needed. Right now, you can cast the controller `self.view`, because it happens to be the text view itself, but that’s not really reliable. Does that seems reasonable? If so, you can update your PR accordingly, and I’ll merge it.

**Comment by mouhcine** [comment]
Subclassing may not be the best solution if what one wants is to customise the appearance of "private" UI elements.

I have a need of changing the fonts and colors of all texts in `VTAcknowledgementsViewController` and I didn't want to rush into code as you still need to decide how to handle this.

My initial idea was to to have an `attributes` property for each label in the view. It would offer a bit more flexibility than `licenseTextViewFont`.

What do you think about this @vtourraine ?

**Comment by vtourraine** [comment]
Alright, sorry for the late decision. I’m closing this PR, and I’ve pushed bcdcde3bdbed3bdddf3644bf0f19eccef9b87bd3. It removes the `textViewFont ` property, because that was an early addition that doesn’t make a lot of sense now, and adds a `textView` property instead. 

I’m sorry if that makes things more complicated for specific changes, but I believe it’s for the best in most cases.

**Pull request closed without merging**
