### PR TITLE
tvOS support #47

### PR DESCRIPTION
**Pull request by alexpalman**
Added tvOS support.
It works on tvOS with the changes I made, but the UITextView containing the license text scrolls under the transparent navigation bar, which looks incorrect.
That shouldn't be a deal breaker though, because the text is still readable.

### CODE REVIEW

**Comment by vtourraine** [comment]
Hello Alex. Sorry about being so slow to comment on this PR (🐢), and thanks for contributing (👍)!

It seems like you made the appropriate changes for the view controllers and the podspec, which is great. 

But I think we still need to work on the Xcode project for the framework itself. In the new target for tvOS, we should add the source files to actually compile something, and we should remove the new Info.plist and general header files, and point to the existing files from the main iOS target instead.

I hope that makes sense. You can look at [AFNetworking](https://github.com/AFNetworking/AFNetworking) as an example, it already implements the same approach. And if you prefer that I make these changes, just let me know and I’ll work on your branch.

**Comment by alexpalman** [comment]
Hi,
no problemo :)
Sorry, I have overlooked that because I immediately tried it in my tvOS project.
I'll make the necessary changes soonish and update the PR accordingly 👍.

Thanks for looking into it!

**Comment by alexpalman** [comment]
Sorry for the long delay, but I finally updated the branch. Should be building correctly now.

**Comment by vtourraine** [comment]
Awesome! 📺 

Now I’ll wait for a couple of days/weeks to see if we receive feedback on these changes, then I’ll ship it with version 1.1.

Thank you once again for this PR.

**Pull request merged**
